/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Emprestimo.java
 *
 * Created on 22/05/2012, 19:45:06
 */

package br.com.anhanguera.pos.biblioteca.ui;

import br.com.anhanguera.pos.biblioteca.controller.EmprestimoController;
import br.com.anhanguera.pos.biblioteca.controller.ObraController;
import br.com.anhanguera.pos.biblioteca.entidade.Obra;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class Emprestimo extends javax.swing.JFrame {

    /** Creates new form Emprestimo */
    public Emprestimo() {
        initComponents();
        initNomeObra(new ObraController().selectAll());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmprestimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeObra = new javax.swing.JTextField();
        txtCodigoFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ccbTest = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEmprestimo.setText("Salvar");
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        jLabel1.setText("Informe a Obra:");

        jLabel3.setText("Informe o seu Numero de Matricula:");

        jLabel4.setText("Informe Numero de Matricula Funcionario:");

        ccbTest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeObra, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNomeMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)))
                    .addComponent(btnEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ccbTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ccbTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnEmprestimo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void initNomeObra(List<Obra> _Obra){
        try{
            DefaultComboBoxModel comboModel = (DefaultComboBoxModel) ccbTest.getModel();
            comboModel.removeAllElements();
            
            if(_Obra != null){
                for(Obra d : _Obra){
                    comboModel.addElement(d.getTituloObra());
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        br.com.anhanguera.pos.biblioteca.entidade.Emprestimo emprestimo = new br.com.anhanguera.pos.biblioteca.entidade.Emprestimo();

        Calendar Data = Calendar.getInstance();

        emprestimo.setNomeObra(txtNomeObra.getText());


        Object obj = ccbTest.getSelectedItem();
        JOptionPane.showMessageDialog(null, obj.toString());

        
        emprestimo.setNumeroMatricula(txtNomeMatricula.getText());
        emprestimo.setDataCriacao(Data.getTime());
        Data.add(Data.DATE, 5);
        emprestimo.setDataDevolucao(Data.getTime());
        emprestimo.setCodigFuncionario(txtCodigoFuncionario.getText());

        
        if(new EmprestimoController(emprestimo).insert())
            JOptionPane.showMessageDialog(null, "Emprestimo feito com sucesso.");
        else
            JOptionPane.showMessageDialog(null, "Não foi possível efetuar o emprestimo.");

    }//GEN-LAST:event_btnEmprestimoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JComboBox ccbTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtNomeMatricula;
    private javax.swing.JTextField txtNomeObra;
    // End of variables declaration//GEN-END:variables



}
