/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.anhanguera.pos.biblioteca.ui;

import br.com.anhanguera.pos.biblioteca.controller.ExemplarController;
import br.com.anhanguera.pos.biblioteca.controller.ObraController;
import br.com.anhanguera.pos.biblioteca.controller.UtilController;
import br.com.anhanguera.pos.biblioteca.entidade.Exemplar;
import br.com.anhanguera.pos.biblioteca.entidade.Obra;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rafaelpoveda
 */
public class ExemplarUI extends javax.swing.JFrame {

    /**
     * Creates new form ExemplarUI
     */
    private boolean bEditar = false;
    private int intCodigoExemplar = 0;
    
    public ExemplarUI() {
        initComponents();
        initComboObra();
    }
    
    public ExemplarUI(Exemplar exemplar){
        initComponents();
        initComboObra();
        txtDtAquisicao.setText(exemplar.getDataAquisicaoExemplar().toString());
        intCodigoExemplar = exemplar.getCodigoExemplar();
        bEditar = true;
    }
    
    private void initComboObra(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxObra.getModel();
        List<Obra> _lstObra = new ObraController().selectAll();
        int count = 0;
        int index = 0;
        for(Obra obra : _lstObra){
            model.addElement(obra.getCodigoObra() + "-" + obra.getTituloObra());
            if(obra.getCodigoObra() == intCodigoExemplar)
                index = count;
            count++;
        }
        
        cbxObra.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxObra = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtDtAquisicao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxSituacao = new javax.swing.JComboBox();
        btnCad = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Exemplar");

        jLabel1.setText("Obra");

        jLabel2.setText("Data aquisição");

        jLabel3.setText("Situação");

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponível", "Emprestado" }));

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(txtDtAquisicao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnCad)
                        .add(18, 18, 18)
                        .add(btnCancel))
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(cbxObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(71, 71, 71)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cbxSituacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbxObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbxSituacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtDtAquisicao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnCad)
                    .add(btnCancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        Exemplar exemplar = new Exemplar();
        Obra obra = new Obra();
        int intCodigoObra = Integer.parseInt(cbxObra.getSelectedItem().toString().split("-")[0]);
        obra.setCodigoObra(intCodigoObra);
        exemplar.setCodigoExemplar(new ExemplarController().nextCodigoExemplar(intCodigoObra));
        exemplar.setDataAquisicaoExemplar(UtilController.convertDate(txtDtAquisicao.getText()));
        exemplar.setSituacaoExemplar(cbxSituacao.getSelectedItem().toString());
        exemplar.setObra(obra);
        
        if(bEditar)
        {
            
            exemplar.setCodigoExemplar(intCodigoExemplar);
            if(new ExemplarController().alter(exemplar))
                JOptionPane.showMessageDialog(null, "Exemplar salvo com sucesso");
            else
                JOptionPane.showMessageDialog(null, "Nao foi possivel salvar o exemplar");
            
        }else{
        if(new ExemplarController().insert(exemplar))
            JOptionPane.showMessageDialog(null, "Exemplar cadastrado com sucesso.");
        else
            JOptionPane.showMessageDialog(null, "Não foi possível salvar o exemplar.");
        }
    }//GEN-LAST:event_btnCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemplarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemplarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemplarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemplarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExemplarUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cbxObra;
    private javax.swing.JComboBox cbxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDtAquisicao;
    // End of variables declaration//GEN-END:variables
}
